# Generated by Django 4.2.6 on 2023-10-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phno',
            field=models.IntegerField(null=True),
        ),
    ]
